### ISSUE TITLE
object has no attribute 'required_historical_candles_count'

### ISSUE THREAD

**Issue by derBG** [techfreaque/octobot-spot-master-3000#2]
Fresh installed version from github

$ git clone https://github.com/Drakkar-Software/OctoBot.git
$ cd OctoBot
$ python start.py 

Added the tentacle and the profile following the guide.

`2023-03-19 18:56:12,931 INFO     OctoBot Launcher     Version : 0.4.43
 2023-03-19 18:56:12,932 INFO     OctoBot Launcher     Loading config files...
 2023-03-19 18:56:12,938 INFO     Configuration        Using default spot master 3000 profile.
 2023-03-19 18:56:12,954 INFO     OctoBot Launcher     Disclaimer accepted by user.
 2023-03-19 18:56:12,956 INFO     Commands             Current imported profile "default spot master 3000" references tentacles in a different version from the current OctoBot. Referenced version: 0.4.36, current OctoBot version: 0.4.43. Please make sure that this profile works on your OctoBot.
 2023-03-19 18:56:14,423 INFO     telethon.crypto.aes  libssl detected, it will be used for encryption
 2023-03-19 18:56:15,830 INFO     OctoBot              Starting OctoBot with real trader on kucoin[spot] trading ETH/USDT, DOT/USDT, BTC/USDT, MATIC/USDT, LTC/USDT, BNB/USDT, ADA/USDT, ICP/USDT, DOGE/USDT, XMR/USDT and using bot_id: 5af11814-3f7c-4150-b015-4c68eda093dc
 2023-03-19 18:56:15,846 INFO     CCXTConnector[kucoin] Creating kucoin SPOT exchange with ccxt in version 2.8.4
 2023-03-19 18:56:15,872 INFO     WebService           Interface successfully initialized and accessible at: http://127.0.1.1:5001.
 2023-03-19 18:56:18,213 INFO     WebSocket - kucoin   Creating kucoin SPOT exchange with ccxt in version 2.8.4
 2023-03-19 18:56:18,240 INFO     ExchangeManager      DefaultWebSocketExchange connected to Kucoin
 2023-03-19 18:56:18,256 INFO     PortfolioManager     Current Portfolio : {}
 2023-03-19 18:56:18,267 ERROR    ExchangeBuilder      An error occurred when initializing trading mode : can't set attribute
 2023-03-19 18:56:18,271 INFO     CCXTConnector[kucoin] Closing connection.
 2023-03-19 18:56:18,291 INFO     CCXTConnector[kucoin] Connection closed.
 2023-03-19 18:56:18,295 ERROR    OctoBotChannelTradingConsumer can't set attribute
Traceback (most recent call last):
  File "octobot_trading/octobot_channel_consumer.py", line 74, in octobot_trading.octobot_channel_consumer._handle_creation
  File "octobot_trading/exchanges/exchange_builder.py", line 47, in build
  File "octobot_trading/exchanges/exchange_builder.py", line 43, in octobot_trading.exchanges.exchange_builder.ExchangeBuilder.build
  File "octobot_trading/exchanges/exchange_builder.py", line 81, in _build_exchange_manager
  File "octobot_trading/exchanges/exchange_builder.py", line 75, in octobot_trading.exchanges.exchange_builder.ExchangeBuilder._build_exchange_manager
  File "octobot_trading/exchanges/exchange_builder.py", line 112, in _build_trading_modes_if_required
  File "octobot_trading/exchanges/exchange_builder.py", line 127, in _build_trading_modes
  File "octobot_trading/exchanges/exchange_builder.py", line 119, in octobot_trading.exchanges.exchange_builder.ExchangeBuilder._build_trading_modes
  File "octobot_trading/modes/modes_factory.py", line 30, in create_trading_modes
  File "octobot_trading/modes/modes_factory.py", line 52, in _create_trading_modes
  File "octobot_trading/modes/modes_factory.py", line 73, in create_trading_mode
  File "/home/pi/OctoBot/OctoBot/tentacles/Trading/Mode/spot_master_3000_trading_mode/spot_master_3000_mode.py", line 19, in __init__
    self.get_script = abstract_mode_base.AbstractBaseMode.get_script
AttributeError: can't set attribute
 2023-03-19 18:56:18,302 ERROR    OctoBotChannelTradingConsumer Error when creating a new kucoin exchange connexion: AttributeError can't set attribute (AttributeError)
 2023-03-19 18:56:18,303 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,304 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,307 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,309 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,310 ERROR    WebSocket - kucoin   kucoin GET https://api.kucoin.com/api/v1/currencies
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 119, in fetch
    async with session_method(yarl.URL(url, encoded=True),
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/pi/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 543, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "octobot_trading/exchanges/connectors/ccxt/ccxt_websocket_connector.py", line 280, in octobot_trading.exchanges.connectors.ccxt.ccxt_websocket_connector.CCXTWebsocketConnector._init_client
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 194, in load_markets
    raise e
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 190, in load_markets
    result = await self.markets_loading
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 179, in load_markets_helper
    currencies = await self.fetch_currencies()
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/kucoin.py", line 709, in fetch_currencies
    response = await self.publicGetCurrencies(params)
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 1319, in request
    return await self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 1316, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/pi/.local/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 157, in fetch
    raise ExchangeNotAvailable(details) from e
ccxt.base.errors.ExchangeNotAvailable: kucoin GET https://api.kucoin.com/api/v1/currencies
 2023-03-19 18:56:18,313 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,317 ERROR    WebSocket - kucoin   Failed to subscribe when creating websocket feed : kucoin GET https://api.kucoin.com/api/v1/currencies (ExchangeNotAvailable)
 2023-03-19 18:56:18,318 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,323 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,324 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,325 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,326 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,327 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,328 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,329 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,330 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,331 ERROR    root                 
NoneType: None
 2023-03-19 18:56:18,331 ERROR    root                 <class 'AttributeError'>: 'NoneType' object has no attribute 'required_historical_candles_count'
NoneType: None
Exception ignored in: 'octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._get_historical_candles_count'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
AttributeError: 'NoneType' object has no attribute 'required_historical_candles_count'
 2023-03-19 18:56:18,446 ERROR    OHLCVUpdater[kucoin] 'NoneType' object has no attribute 'get_symbol_prices'
Traceback (most recent call last):
  File "octobot_trading/exchange_data/ohlcv/channel/ohlcv_updater.py", line 76, in octobot_trading.exchange_data.ohlcv.channel.ohlcv_updater.OHLCVUpdater._initialize
  File "octobot_trading/exchange_data/ohlcv/channel/ohlcv_updater.py", line 128, in _initialize_candles
  File "octobot_trading/exchange_data/ohlcv/channel/ohlcv_updater.py", line 115, in _get_init_candles
AttributeError: 'NoneType' object has no attribute 'get_symbol_prices'
 2023-03-19 18:56:18,447 ERROR    OHLCVUpdater[kucoin] Error while initializing candles: 'NoneType' object has no attribute 'get_symbol_prices' (AttributeError)
 2023-03-19 18:56:26,555 ERROR    engineio.server      Invalid websocket upgrade (further occurrences of this error will be logged with level INFO)
`

**Comment by techfreaque** [comment]
I'll push a fix soon so it works with the default profile, meanwhile you should be able to use it with a copy of a default profile, just switch to spot master mode. But havent tested it on the pip version yet

**Comment by derBG** [comment]
It works so far.  Thanks

Now i get 
`INFO     SpotMaster3000Mode   Failed to execution user generated custom trading scriptunreadable attribute`

**Comment by techfreaque** [comment]
> INFO SpotMaster3000Mode Failed to execution user generated custom trading scriptunreadable attribute

You can ignore the warning, this is a non official feature on top, that allows you to execute a custom script after the trading mode is done.
Its under user/profiles/profile_name/specific_config/profile_trading_script.py
Currently its not working on all OctoBot versions, but soon it will.

With the latest version you should also be able to use the profile from my repos again.
